### ISSUE TITLE
https://git.familie-radermacher.ch down

### ISSUE THREAD

**Issue by markus2330** [HenrikBengtsson/brother-ptouch-label-printer-on-linux#7]
Is there some fork of it?

Why not have a complete fork here?

In any case links would need to be fixed.

**Comment by HenrikBengtsson** [comment]
Not that I look frequently, but I'd say it's rare that the upstream server is down.

> Why not have a complete fork here?

This repo is mainly for documentation. Its issue tracker has also turned out to be useful - I guess it allows users to have a common forum, which upstream repo does not provide 

But, I don't really want to be in the backup business. I also don't want blur who's the author of `ptouch-print` is - I get the feeling that some people ending up here, think this is the home of the tool. So, I prefer the original author gets the download traffic of their tool. TI know mirroring can easily be done by a GitHub Action's cron job, but it's not a technical decision. That said, if the upstream stream repo gets shaky in the future, we could mirror it here.
